### PR TITLE
macOS build

### PR DESCRIPTION
**Pull request by tomstokes**
Enable compilation on macOS.

### CODE REVIEW

**Comment by fpagliughi** [comment]
Hey, thanks for the PR! I was vaguely aware that this would be possible, but didn't realize it would be possible with 5 lines of code! Nice. I have a MacBook somewhere and will pull it out and give it a test.

Ugh. But, of course, now someone will ask if we can do this for Windows as well.

**Comment by tomstokes** [comment]
Credit to Analog Devices for making libiio cross-platform in the first place. I've been using this crate with IIO on my Mac in a very limited context for a while without issues. Would be good to have some more testing on this, though.

**Comment by fpagliughi** [comment]
Still haven't found my MacBook. I know it's around here somewhere!
But for now, this doesn't seem to break anything, so I'll merge and give it to the ether for further testing.

**Comment by tomstokes** [comment]
Thanks for merging. I'm likely the only person using this right now, but I haven't run into any problems yet.

I'll continue testing and submit and PRs if I run into issues.

**Comment by fpagliughi** [comment]
I have an app in production that uses this library. Once I get it updated to this version, a few Mac users will likely start testing it, so we should have some additional feedback in a week or two.

**Comment by fpagliughi** [comment]
@tomstokes I found my MacBook and tried to build. It failed, unable to find the library, and when I looked, my `/opt` directory was empty. Looking at my homebrew config:

```
 % brew config | grep HOMEBREW
HOMEBREW_VERSION: 3.3.12
HOMEBREW_PREFIX: /usr/local
...
```

Looking under there, I found the directory, `/usr/local/Frameworks`, and when I plugged that in to 'build.rs', it built quite nicely.

So I guess we need a way to find the right directory in the build?

**Comment by fpagliughi** [comment]
I created a new Issue to track the problem.
https://github.com/fpagliughi/rust-industrial-io/issues/18

**Pull request merged**
